# Generated by Django 3.1.7 on 2021-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(default=3)),
                ('status', models.SmallIntegerField(default=0)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
                ('updatetime', models.FloatField(default=0.0, max_length=30)),
                ('role_id', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mark', models.TextField(default='')),
                ('avatar', models.CharField(default='', max_length=255)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
