# Generated by Django 3.1.7 on 2021-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(default=0)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
                ('updatetime', models.FloatField(default=0.0, max_length=30)),
                ('mark', models.TextField(default='')),
            ],
        ),
    ]
