# Generated by Django 3.1.7 on 2021-03-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logistics_logisticstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='type_price',
            field=models.IntegerField(default=0),
        ),
    ]
