# Generated by Django 3.1.7 on 2021-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logistics_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='maddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logistics',
            name='number',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='logistics',
            name='raddress',
            field=models.CharField(default='', max_length=255),
        ),
    ]
