# Generated by Django 3.1.7 on 2021-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210307_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='weight',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='type_price',
            field=models.IntegerField(default=1),
        ),
    ]
