# Generated by Django 3.1.7 on 2021-03-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210307_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='unit_price',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
