# Generated by Django 3.1.7 on 2021-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logistics_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=15)),
                ('city', models.CharField(default='', max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
                ('updatetime', models.FloatField(default=0.0, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='logistics',
            name='sn',
            field=models.CharField(default='', max_length=21),
        ),
    ]
