# Generated by Django 3.1.7 on 2021-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210308_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='intime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='logistics',
            name='outtime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
