# Generated by Django 3.1.7 on 2021-03-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210309_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='types',
            new_name='intypes',
        ),
        migrations.AddField(
            model_name='logistics',
            name='apptime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='logistics',
            name='outtypes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
