# Generated by Django 3.1.7 on 2021-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_logisticsrecord_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='arrtime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='logistics',
            name='picktime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
