# Generated by Django 3.1.7 on 2021-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210310_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='pickmark',
            field=models.TextField(default=''),
        ),
    ]
