# Generated by Django 3.1.7 on 2021-03-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_logistics_pickmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='pickmark',
            new_name='appmark',
        ),
    ]
