# Generated by Django 3.1.7 on 2021-03-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210310_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='take_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logistics',
            name='taketime',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
